// flow-typed signature: df7f911b3a70d4a51ddb5b95c12cc7d9
// flow-typed version: <<STUB>>/micro-redirect_v^1.0.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'micro-redirect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'micro-redirect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'micro-redirect/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'micro-redirect/index' {
  declare module.exports: $Exports<'micro-redirect'>;
}
declare module 'micro-redirect/index.js' {
  declare module.exports: $Exports<'micro-redirect'>;
}
declare module 'micro-redirect/index.test.js' {
  declare module.exports: $Exports<'micro-redirect/index.test'>;
}
