// flow-typed signature: df27b754a7b2f42be592f4fd84cc80b3
// flow-typed version: <<STUB>>/next-workbox-webpack-plugin_v^1.1.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-workbox-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-workbox-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-workbox-webpack-plugin/bin/next-workbox-start' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next-workbox-webpack-plugin/bin/next-workbox-start.js' {
  declare module.exports: $Exports<'next-workbox-webpack-plugin/bin/next-workbox-start'>;
}
declare module 'next-workbox-webpack-plugin/index' {
  declare module.exports: $Exports<'next-workbox-webpack-plugin'>;
}
declare module 'next-workbox-webpack-plugin/index.js' {
  declare module.exports: $Exports<'next-workbox-webpack-plugin'>;
}
