// flow-typed signature: b88f76b63390a9b2763275ea583b5488
// flow-typed version: <<STUB>>/next-workbox-webpack-plugin_v^2.1.1/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-workbox-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-workbox-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-workbox-webpack-plugin/bin/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next-workbox-webpack-plugin/bin/server.js' {
  declare module.exports: $Exports<'next-workbox-webpack-plugin/bin/server'>;
}
declare module 'next-workbox-webpack-plugin/index' {
  declare module.exports: $Exports<'next-workbox-webpack-plugin'>;
}
declare module 'next-workbox-webpack-plugin/index.js' {
  declare module.exports: $Exports<'next-workbox-webpack-plugin'>;
}
