// flow-typed signature: 87deab33164007a413e8463e25b557f2
// flow-typed version: <<STUB>>/wikidata-sdk_v^5.15.4/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wikidata-sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wikidata-sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wikidata-sdk/dist/wikidata-sdk' {
  declare module.exports: any;
}

declare module 'wikidata-sdk/dist/wikidata-sdk.min' {
  declare module.exports: any;
}

declare module 'wikidata-sdk/lib/helpers/helpers' {
  declare module.exports: any;
}

declare module 'wikidata-sdk/lib/helpers/parse_claim' {
  declare module.exports: any;
}

declare module 'wikidata-sdk/lib/helpers/parse_responses' {
  declare module.exports: any;
}

declare module 'wikidata-sdk/lib/helpers/simplify_claims' {
  declare module.exports: any;
}

declare module 'wikidata-sdk/lib/helpers/simplify_entity' {
  declare module.exports: any;
}

declare module 'wikidata-sdk/lib/helpers/simplify_sitelinks' {
  declare module.exports: any;
}

declare module 'wikidata-sdk/lib/helpers/simplify_sparql_results' {
  declare module.exports: any;
}

declare module 'wikidata-sdk/lib/helpers/simplify_text_attributes' {
  declare module.exports: any;
}

declare module 'wikidata-sdk/lib/helpers/sitelinks_helpers' {
  declare module.exports: any;
}

declare module 'wikidata-sdk/lib/helpers/sitelinks_languages' {
  declare module.exports: any;
}

declare module 'wikidata-sdk/lib/helpers/wikidata_time_to_date_object' {
  declare module.exports: any;
}

declare module 'wikidata-sdk/lib/index' {
  declare module.exports: any;
}

declare module 'wikidata-sdk/lib/queries/get_entities_from_sitelinks' {
  declare module.exports: any;
}

declare module 'wikidata-sdk/lib/queries/get_entities' {
  declare module.exports: any;
}

declare module 'wikidata-sdk/lib/queries/get_many_entities' {
  declare module.exports: any;
}

declare module 'wikidata-sdk/lib/queries/get_reverse_claims' {
  declare module.exports: any;
}

declare module 'wikidata-sdk/lib/queries/get_revisions' {
  declare module.exports: any;
}

declare module 'wikidata-sdk/lib/queries/search_entities' {
  declare module.exports: any;
}

declare module 'wikidata-sdk/lib/queries/sparql_query' {
  declare module.exports: any;
}

declare module 'wikidata-sdk/lib/utils/build_url' {
  declare module.exports: any;
}

declare module 'wikidata-sdk/lib/utils/querystring_lite' {
  declare module.exports: any;
}

declare module 'wikidata-sdk/lib/utils/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wikidata-sdk/dist/wikidata-sdk.js' {
  declare module.exports: $Exports<'wikidata-sdk/dist/wikidata-sdk'>;
}
declare module 'wikidata-sdk/dist/wikidata-sdk.min.js' {
  declare module.exports: $Exports<'wikidata-sdk/dist/wikidata-sdk.min'>;
}
declare module 'wikidata-sdk/lib/helpers/helpers.js' {
  declare module.exports: $Exports<'wikidata-sdk/lib/helpers/helpers'>;
}
declare module 'wikidata-sdk/lib/helpers/parse_claim.js' {
  declare module.exports: $Exports<'wikidata-sdk/lib/helpers/parse_claim'>;
}
declare module 'wikidata-sdk/lib/helpers/parse_responses.js' {
  declare module.exports: $Exports<'wikidata-sdk/lib/helpers/parse_responses'>;
}
declare module 'wikidata-sdk/lib/helpers/simplify_claims.js' {
  declare module.exports: $Exports<'wikidata-sdk/lib/helpers/simplify_claims'>;
}
declare module 'wikidata-sdk/lib/helpers/simplify_entity.js' {
  declare module.exports: $Exports<'wikidata-sdk/lib/helpers/simplify_entity'>;
}
declare module 'wikidata-sdk/lib/helpers/simplify_sitelinks.js' {
  declare module.exports: $Exports<'wikidata-sdk/lib/helpers/simplify_sitelinks'>;
}
declare module 'wikidata-sdk/lib/helpers/simplify_sparql_results.js' {
  declare module.exports: $Exports<'wikidata-sdk/lib/helpers/simplify_sparql_results'>;
}
declare module 'wikidata-sdk/lib/helpers/simplify_text_attributes.js' {
  declare module.exports: $Exports<'wikidata-sdk/lib/helpers/simplify_text_attributes'>;
}
declare module 'wikidata-sdk/lib/helpers/sitelinks_helpers.js' {
  declare module.exports: $Exports<'wikidata-sdk/lib/helpers/sitelinks_helpers'>;
}
declare module 'wikidata-sdk/lib/helpers/sitelinks_languages.js' {
  declare module.exports: $Exports<'wikidata-sdk/lib/helpers/sitelinks_languages'>;
}
declare module 'wikidata-sdk/lib/helpers/wikidata_time_to_date_object.js' {
  declare module.exports: $Exports<'wikidata-sdk/lib/helpers/wikidata_time_to_date_object'>;
}
declare module 'wikidata-sdk/lib/index.js' {
  declare module.exports: $Exports<'wikidata-sdk/lib/index'>;
}
declare module 'wikidata-sdk/lib/queries/get_entities_from_sitelinks.js' {
  declare module.exports: $Exports<'wikidata-sdk/lib/queries/get_entities_from_sitelinks'>;
}
declare module 'wikidata-sdk/lib/queries/get_entities.js' {
  declare module.exports: $Exports<'wikidata-sdk/lib/queries/get_entities'>;
}
declare module 'wikidata-sdk/lib/queries/get_many_entities.js' {
  declare module.exports: $Exports<'wikidata-sdk/lib/queries/get_many_entities'>;
}
declare module 'wikidata-sdk/lib/queries/get_reverse_claims.js' {
  declare module.exports: $Exports<'wikidata-sdk/lib/queries/get_reverse_claims'>;
}
declare module 'wikidata-sdk/lib/queries/get_revisions.js' {
  declare module.exports: $Exports<'wikidata-sdk/lib/queries/get_revisions'>;
}
declare module 'wikidata-sdk/lib/queries/search_entities.js' {
  declare module.exports: $Exports<'wikidata-sdk/lib/queries/search_entities'>;
}
declare module 'wikidata-sdk/lib/queries/sparql_query.js' {
  declare module.exports: $Exports<'wikidata-sdk/lib/queries/sparql_query'>;
}
declare module 'wikidata-sdk/lib/utils/build_url.js' {
  declare module.exports: $Exports<'wikidata-sdk/lib/utils/build_url'>;
}
declare module 'wikidata-sdk/lib/utils/querystring_lite.js' {
  declare module.exports: $Exports<'wikidata-sdk/lib/utils/querystring_lite'>;
}
declare module 'wikidata-sdk/lib/utils/utils.js' {
  declare module.exports: $Exports<'wikidata-sdk/lib/utils/utils'>;
}
